package uit.edu.project.layertest.UISwing;

import java.awt.event.ActionEvent;

import javax.swing.JDesktopPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import uit.edu.project.layertest.UISwing.doctor.InsertDrFrame;
import uit.edu.project.layertest.UISwing.doctor.ViewDrFrame;
import uit.edu.project.layertest.UISwing.patient.InsertPatientFrame;
import uit.edu.project.layertest.UISwing.patient.ViewPatientFrame;

/**
 *
 * @author thawaye
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpDesktop = new javax.swing.JDesktopPane();
        mnbMain = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniExit = new javax.swing.JMenuItem();
        mnuDoctor = new javax.swing.JMenu();
        mniNewDoctor = new javax.swing.JMenuItem();
        sep01 = new javax.swing.JPopupMenu.Separator();
        mniViewDoctors = new javax.swing.JMenuItem();
        mnuPatient = new javax.swing.JMenu();
        mniNewPatient = new javax.swing.JMenuItem();
        sep02 = new javax.swing.JPopupMenu.Separator();
        mniViewPatients = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpDesktopLayout = new javax.swing.GroupLayout(dpDesktop);
        dpDesktop.setLayout(dpDesktopLayout);
        dpDesktopLayout.setHorizontalGroup(
            dpDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dpDesktopLayout.setVerticalGroup(
            dpDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnuFile.setText("File");
        mnuFile.setMargin(new java.awt.Insets(0, 0, 0, 16));

        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniExit);

        mnbMain.add(mnuFile);

        mnuDoctor.setText("Doctor");
        mnuDoctor.setMargin(new java.awt.Insets(0, 0, 0, 16));

        mniNewDoctor.setText("New Doctor");
        mniNewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNewDoctorActionPerformed(evt);
            }
        });
        mnuDoctor.add(mniNewDoctor);
        

        mniViewDoctors.setText("View Doctors");       
        mniViewDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInsertPatientActionPerformed(evt);
            }
        });
        mnuDoctor.add(mniViewDoctors);
        mnuDoctor.add(sep01);

        mnbMain.add(mnuDoctor);

        mnuPatient.setText("Patient");

        mniNewPatient.setText("New Patient");
        mnuPatient.add(mniNewPatient);
        mnuPatient.add(sep02);
        mniNewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewDoctorActionPerformed(evt);
            }
        });

        mniViewPatients.setText("View Patients");
        mnuPatient.add(mniViewPatients);
        mniViewPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniViewPatientActionPerformed(evt);
            }
        });

        mnbMain.add(mnuPatient);

        setJMenuBar(mnbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    
    private void mniNewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNewDoctorActionPerformed
        UIManager.shownInDesktopPane(this.dpDesktop, InsertDrFrame.class);
    }//GEN-LAST:event_mniNewDoctorActionPerformed

    
    private void mniViewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNewDoctorActionPerformed
        UIManager.shownInDesktopPane(this.dpDesktop, ViewDrFrame.class);
    }
    
    private void mniInsertPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNewDoctorActionPerformed
        UIManager.shownInDesktopPane(this.dpDesktop, InsertPatientFrame.class);
       
    }
    private void mniViewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNewDoctorActionPerformed
        UIManager.shownInDesktopPane(this.dpDesktop, ViewPatientFrame.class);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpDesktop;
    private javax.swing.JMenuBar mnbMain;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniNewDoctor;
    private javax.swing.JMenuItem mniNewPatient;
    private javax.swing.JMenuItem mniViewDoctors;
    private javax.swing.JMenuItem mniViewPatients;
    private javax.swing.JMenu mnuDoctor;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuPatient;
    private javax.swing.JPopupMenu.Separator sep01;
    private javax.swing.JPopupMenu.Separator sep02;
    // End of variables declaration//GEN-END:variables
}
